import type { Recipe, StylePreset } from './types.js';
const base: Recipe = { material: 'none', detail: .65, shape: 'square', border: 'frame', texture: 'none', eye: 'square', effect: 'none', animation: 'none', foreground: '#172f2a', background: '#fffdf5', accent: '#385b47', gradient: false, seed: 42 };
const preset = (id: string, name: string, description: string, inspiration: string, recipe: Partial<Recipe>, safety: StylePreset['safety'] = 'conservative', credit?: StylePreset['credit']): StylePreset => ({ id, name, description, inspiration, safety, credit, recipe: { ...base, ...recipe } });
const source = (name: string, url: string, technique: string): NonNullable<StylePreset['credit']> => ({ name, url, technique });
const styling = (technique: string) => source('qr-code-styling', 'https://github.com/kozakdenys/qr-code-styling', technique);
const liquid = (technique: string) => source('liquid-js QR Code Styling', 'https://liquid-js.github.io/qr-code-styling/enums/index.DotType.html', technique);
const artistic = (technique: string) => source('artistic_qr', 'https://github.com/deaa-jahjah/artistic_qr', technique);
const pythonQR = (technique: string) => source('python-qrcode', 'https://github.com/lincolnloop/python-qrcode', technique);
const verevoir = (technique: string) => source('verevoir/qr', 'https://github.com/verevoir/qr', technique);
const dagron = (technique: string) => source('dagronf/QRCode', 'https://github.com/dagronf/QRCode', technique);
export const presets: readonly StylePreset[] = [
  preset('editorial', 'Editorial', 'Crisp ink, warm stock, and a double-rule frame.', 'Book jackets · menus · invitations', {}),
  preset('soft-stone', 'Soft stone', 'Rounded blocks in quiet slate with a paper finish.', 'Wellness · ceramics · hospitality', { shape: 'rounded', foreground: '#343b48', accent: '#4c5767', texture: 'paper' }),
  preset('orbital', 'Orbital', 'An array of dots surrounded by planetary arcs.', 'Science · music · exhibitions', { shape: 'dots', border: 'orbit', foreground: '#242050', accent: '#42357d', background: '#f6f3ff' }, 'experimental'),
  preset('prism', 'Prism', 'Faceted diamond modules with a deep jewel gradient.', 'Jewelry · packaging · fashion', { shape: 'diamond', border: 'deco', foreground: '#38224c', accent: '#173e64', gradient: true }, 'experimental'),
  preset('candy', 'Candy', 'Plump squircles, berry ink, and a ticket-shaped surround.', 'Bakeries · celebrations · pop-ups', { shape: 'squircle', border: 'ticket', foreground: '#761f43', accent: '#5c234d', background: '#fff2f5' }),
  preset('signal', 'Signal', 'Horizontal ribbons flow through a technical grid.', 'Technology · wayfinding · conferences', { shape: 'horizontal', border: 'grid', foreground: '#153d5c', accent: '#245778', background: '#f2faff' }),
  preset('reeds', 'Reeds', 'Vertical strokes with a botanical border in forest ink.', 'Gardens · outdoor spaces · farm shops', { shape: 'vertical', border: 'botanical', foreground: '#214937', accent: '#375b35', texture: 'paper' }),
  preset('woven', 'Woven', 'Alternating threads suggest a woven indigo textile.', 'Textiles · craft markets · makers', { shape: 'weave', border: 'frame', foreground: '#252f58', accent: '#374267', texture: 'lines' }, 'experimental'),
  preset('terrazzo', 'Terrazzo', 'Seeded, gently irregular tiles with a speckled surround.', 'Architecture · interiors · ceramics', { shape: 'mosaic', border: 'frame', texture: 'speckle', foreground: '#533829', accent: '#654129', background: '#fff6e8' }, 'experimental'),
  preset('circuit', 'Circuit', 'Connected traces and contact points in deep teal.', 'Electronics · workshops · hardware', { shape: 'circuit', border: 'grid', foreground: '#123d3f', accent: '#13534c', background: '#effcf8' }, 'experimental'),
  preset('botanical', 'Botanical', 'Leaf-like modules framed by delicate growing stems.', 'Florists · tea · natural products', { shape: 'petal', border: 'botanical', foreground: '#304524', accent: '#4d5427', background: '#fbf9ed', texture: 'paper' }, 'experimental'),
  preset('letterpress', 'Letterpress', 'Variable ink dots and a perforated postage border.', 'Postcards · zines · heritage brands', { shape: 'halftone', border: 'postage', foreground: '#512d29', accent: '#65382e', background: '#fff5e6', texture: 'speckle' }, 'experimental'),
  preset('bamboo', 'Bamboo', 'Segmented canes with joints, longitudinal fibers, and a woven bamboo surround.', 'Tea houses · gardens · natural packaging', { material: 'bamboo', border: 'none', foreground: '#23451c', accent: '#56742d', background: '#fafbe9' }, 'experimental'),
  preset('oak', 'Oak', 'Carved end grain, elongated fibers, and knots flow across the code.', 'Woodworkers · furniture · distilleries', { material: 'oak', border: 'none', foreground: '#4d2c16', accent: '#85602e', background: '#fff4df' }, 'experimental'),
  preset('beans', 'Beans', 'Roasted beans with curved center creases, rounded volume, and seeded rotation.', 'Coffee roasters · cafés · food labels', { material: 'beans', border: 'none', foreground: '#3d221a', accent: '#79543b', background: '#fff5e8' }, 'experimental'),
  preset('ants', 'Ants', 'Six-legged silhouettes with antennae and segmented bodies form a busy colony.', 'Ecology · museums · field guides', { material: 'ants', border: 'none', foreground: '#2b2521', accent: '#766050', background: '#faf7ec' }, 'experimental'),
  preset('fire', 'Fire', 'Curling flame tongues, ember highlights, and a flickering flame surround.', 'Hot sauce · festivals · kitchens', { material: 'fire', border: 'none', foreground: '#7a2412', accent: '#d05d17', background: '#fff5e5' }, 'experimental'),
  preset('ice', 'Ice', 'Fractured crystal facets with branching cracks and reflective edges.', 'Winter events · cold drinks · science', { material: 'ice', border: 'none', foreground: '#184362', accent: '#438ba8', background: '#f1fcff' }, 'experimental'),
  preset('clouds', 'Clouds', 'Billowing storm-cloud silhouettes, overlapping lobes, and soft highlights.', 'Weather · travel · dream journals', { material: 'clouds', border: 'none', foreground: '#364358', accent: '#7185a0', background: '#f7fbff' }, 'experimental'),
  preset('ripples', 'Ripples', 'Overlapping wave fronts travel through a continuous watery surface.', 'Spas · pools · conservation', { material: 'ripples', border: 'none', foreground: '#164957', accent: '#3b8492', background: '#effdff' }, 'experimental'),
  preset('leaves', 'Leaves', 'Interleaved leaf silhouettes with central ribs and branching veins.', 'Nurseries · botanical collections · tea', { material: 'leaves', border: 'none', foreground: '#28451d', accent: '#638139', background: '#f7fbe9' }, 'experimental'),
  preset('classy-noir', 'Classy noir', 'Neighbor-aware rounds join into soft ligatures with rounded finder eyes.', 'Luxury labels · portfolios · night menus', { shape: 'classy', eye: 'rounded', foreground: '#18171a', accent: '#4c4652', background: '#fffdf8' }, 'experimental', styling('classy and rounded module geometry with separately styled finder patterns')),
  preset('honeycomb', 'Honeycomb', 'Tight hexagonal cells and diamond finder eyes form a precise hive.', 'Apiaries · science · geometric identities', { shape: 'hexagon', eye: 'diamond', border: 'grid', foreground: '#4b3210', accent: '#76510f', background: '#fff9e5', gradient: true }, 'experimental', liquid('hexagon modules and custom finder geometry')),
  preset('constellation', 'Constellation', 'Dense stars orbit circular finder eyes on midnight paper.', 'Astronomy · nightlife · album art', { shape: 'star', eye: 'dots', border: 'orbit', foreground: '#23234e', accent: '#5b4484', background: '#fbf9ff' }, 'experimental', liquid('star modules')),
  preset('love-letter', 'Love letter', 'Heart modules, berry ink, and a postage edge turn a link into a keepsake.', 'Weddings · gifts · personal notes', { shape: 'heart', eye: 'rounded', border: 'postage', foreground: '#6e1837', accent: '#a33e5d', background: '#fff5f7' }, 'experimental', liquid('heart modules')),
  preset('waypoint', 'Waypoint', 'Compact crosses and diamond eyes create a map-like field of markers.', 'Maps · trails · games · events', { shape: 'cross', eye: 'diamond', border: 'grid', foreground: '#173e51', accent: '#357083', background: '#f2fbfc' }, 'experimental', liquid('plus and diamond module vocabulary')),
  preset('liquid-ink', 'Liquid ink', 'Seeded organic blobs pool around softened finder eyes.', 'Music · galleries · experimental packaging', { shape: 'fluid', eye: 'rounded', border: 'none', foreground: '#26203e', accent: '#553a77', background: '#fbf8ff', gradient: true }, 'experimental', liquid('blob and soft module families')),
  preset('cross-stitch', 'Cross stitch', 'Every dark cell becomes an oversized thread cross on warm fabric.', 'Embroidery · handmade gifts · pattern charts', { shape: 'stitch', border: 'frame', texture: 'paper', foreground: '#253e61', accent: '#9a5f35', background: '#fff9ea' }, 'experimental', source('XStitchify QR Generator', 'https://xstitchify.com/qr/', 'scan-aware cross-stitch QR patterns with a preserved quiet zone')),
  preset('perler', 'Perler beads', 'Glossy round beads sit on a clean pegboard-like field.', 'Fuse beads · classroom projects · mosaics', { shape: 'bead', eye: 'dots', border: 'grid', foreground: '#174844', accent: '#287a68', background: '#f3fff9', gradient: true }, 'experimental', source('MakeBead QR Pattern Maker', 'https://makebead.com/qr-code-pattern-maker/', 'bead, LEGO, tile, and craft-grid QR patterns')),
  preset('isometric', 'Isometric blocks', 'Faceted cube cells gain a small colored extrusion for dimensional depth.', 'Architecture · 3D studios · games', { shape: 'cube', eye: 'diamond', effect: 'extrude', border: 'none', foreground: '#24394a', accent: '#b56a37', background: '#f8f5ed' }, 'experimental', artistic('isometric and extruded QR effects')),
  preset('debossed', 'Debossed paper', 'Beveled highlights and shadows press rounded modules into fibrous stock.', 'Stationery · invitations · premium packaging', { shape: 'rounded', eye: 'rounded', effect: 'emboss', texture: 'paper', foreground: '#3e3830', accent: '#786b5e', background: '#fffaf0' }, 'experimental', artistic('emboss and bevel lighting effects')),
  preset('floating-sticker', 'Floating sticker', 'Soft shadows lift plump modules above a clean pale surface.', 'Stickers · playful brands · app launches', { shape: 'squircle', eye: 'rounded', effect: 'shadow', border: 'ticket', foreground: '#26395d', accent: '#6d78a6', background: '#f8f9ff' }, 'experimental', artistic('floating sticker and shadow effects')),
  preset('neon-beacon', 'Neon beacon', 'Glowing cyan dots and circular eyes burn against a pale gallery plate.', 'Night events · music · digital signage', { shape: 'dots', eye: 'dots', effect: 'neon', border: 'grid', foreground: '#064b55', accent: '#006873', background: '#efffff', gradient: true }, 'experimental', source('aesthetic-qr-codes', 'https://github.com/ava-avant-iconic/aesthetic-qr-codes', 'neon glow and luminous dot treatments')),
  preset('gradient-sweep', 'Gradient sweep', 'A living gradient travels across joined modules while the resting geometry stays intact.', 'Digital tickets · launch pages · screen displays', { shape: 'classy', eye: 'rounded', animation: 'sweep', border: 'none', foreground: '#183f5c', accent: '#772f67', background: '#faf8ff', gradient: true }, 'experimental', artistic('animated gradient sweep')),
  preset('slow-pulse', 'Slow pulse', 'The complete ink layer breathes gently without changing its geometry.', 'Screen installations · exhibits · ambient links', { shape: 'rounded', eye: 'rounded', animation: 'pulse', border: 'orbit', foreground: '#243b32', accent: '#44644f', background: '#f7fcf4' }, 'experimental', source('AnimateQR', 'https://openreview.net/pdf/e49b2c2a17aafc94e363837c5d5f96b1f06e2e6e.pdf', 'animated QR codes with temporal scan robustness')),
  preset('tilework', 'Tilework', 'Even gaps separate crisp square tiles across warm porcelain.', 'Ceramics · interiors · signage', { shape: 'gapped', border: 'grid', foreground: '#233e50', background: '#fffaf0' }, 'experimental', pythonQR('gapped square drawer; local 80% width tiles')),
  preset('rounded-contour', 'Rounded contour', 'Only exposed corners round off; neighboring cells keep full shared edges.', 'Identity systems · packaging · galleries', { shape: 'contour', eye: 'rounded', border: 'none', foreground: '#34304c' }, 'experimental', pythonQR('neighbor-aware corner rounding')),
  preset('capsule-rows', 'Capsule rows', 'Horizontal runs end in rounded caps with clear lanes between rows.', 'Transit · editorial · music', { shape: 'horizontal-pill', border: 'frame', foreground: '#183e54', background: '#f5fbff' }, 'experimental', pythonQR('horizontal bar drawer with rounded run ends')),
  preset('capsule-columns', 'Capsule columns', 'Vertical runs become organ pipes with rounded top and bottom ends.', 'Architecture · sound · wayfinding', { shape: 'vertical-pill', border: 'none', foreground: '#49304c', background: '#fff6fd' }, 'experimental', pythonQR('vertical bar drawer with rounded run ends')),
  preset('diagonal-hatch', 'Diagonal hatch', 'Dense diagonal ink strokes turn the grid into an engraved hatch.', 'Printmaking · zines · studio labels', { shape: 'diagonal', border: 'postage', foreground: '#302b25', texture: 'paper' }, 'experimental', verevoir('diagonal line style; local cell-contained strokes')),
  preset('sketchbook', 'Sketchbook', 'Seeded curved pen marks create an irregular hand-drawn rhythm.', 'Illustrators · workshops · notebooks', { shape: 'scribble', border: 'frame', foreground: '#253d60', texture: 'paper' }, 'experimental', verevoir('Bezier scribble style; local seeded cell-local curves')),
  preset('petal-cluster', 'Petal cluster', 'Four overlapping petals form each dark flower around a solid center.', 'Florists · spring events · garden journals', { shape: 'flower', eye: 'rounded', border: 'botanical', foreground: '#5c244f', background: '#fff7fb' }, 'experimental', dagron('flower pixel family; local four-lobed silhouette')),
  preset('micro-grid', 'Micro grid', 'Four little blocks meet at a protected dark center, with fine channels between them.', 'Technology · pixel art · game cards', { shape: 'gridlet', border: 'grid', foreground: '#163d43', background: '#f3fffc' }, 'experimental', dagron('grid2x2 pixel family')),
  preset('arrow-field', 'Arrow field', 'Right-facing arrows make a directional field with solid centers.', 'Trails · navigation · events', { shape: 'arrow', border: 'none', foreground: '#293957', background: '#f6f9ff' }, 'experimental', dagron('arrow pixel family; local broad-shaft arrows')),
  preset('tidal-lines', 'Tidal lines', 'Curved top and bottom edges give each cell the rhythm of a wave.', 'Waterfronts · aquariums · retreats', { shape: 'wave', border: 'orbit', foreground: '#164858', background: '#f1fcff' }, 'experimental', dagron('wave pixel family; local quadratic wave silhouette')),

];
export function getPreset(id = 'editorial'): StylePreset {
  const value = presets.find(p => p.id === id);
  if (!value) throw new Error(`Unknown style "${id}". Choose: ${presets.map(p => p.id).join(', ')}.`);
  return value;
}
